namespace: community
name: asa
readme: README.md
authors:
- Sumit Jaiswal @justjais
description: |
  Ansible collection for community Cisco ASA plugins.
license_file: LICENSE
dependencies:
  "ansible.netcommon": "*"
repository: https://github.com/ansible-collections/community.asa
homepage: https://github.com/ansible-collections/community.asa
issues: https://github.com/ansible-collections/community.asa/issues
tags: [community, cisco, asa, security]
